### ISSUE TITLE
need fixtures 

### ISSUE THREAD

**Issue by Dhevendhirancs** [ember-learn/guides-app#104]
Fixtures are removed from the guides. I really need it. Otherwise could you please suggest some tutorial to use data from model (same as using fixtures)?

**Comment by sivakumar-kailasam** [comment]
Thanks for reaching out. Please refer https://guides.emberjs.com/release/tutorial/model-hook/. 

In case of issues with the content of guides please file an issue at https://github.com/ember-learn/guides-source/issues/
