### ISSUE TITLE
Any plans to make guides-app multilingual?

### ISSUE THREAD

**Issue by erlend-sh** [ember-learn/guides-app#119]
Is multilingual support on the roadmap? The translations themselves are probably harder to pull off than the technical implementation, but I think it's a worthwhile long-term goal.

**Comment by sivakumar-kailasam** [comment]
@erlend-sh Hope this answers your question, https://discuss.emberjs.com/t/doc-translate-how-can-i-help-translate-ember-js-document-into-chinese/14721/4?u=sivakumar_k
