### ISSUE TITLE
Create a 404 route

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-app#17]
Instructions for @rwwagner90 

We need a catch all if a user enters an invalid route. For now, the 404 route should redirect to https://emberjs.com/404. Our deployment env requires that we have an in-app 404 route, and we can't just redirect to https://emberjs.com/404

[docs](https://guides.emberjs.com/v2.18.0/routing/defining-your-routes/#toc_wildcard-globbing-routes)

There's an ongoing project to convert shared website things (like headers, footers, etc) into components that can be reused, but in the meantime we copy/paste. The markup should match https://emberjs.com/404 and more or less match the style. Please put any css in a separate file from the rest of the css, so that when components are ready, we just swap it out.

Markup https://github.com/emberjs/website/blob/master/source/404.html.erb
Relevant css: maybe https://github.com/emberjs/website/blob/master/source/stylesheets/pages/404.css.scss

We still have some work to do on importing fonts/typography styling, so if it doesn't look exactly the same, it's ok. If you match the markup of the website, a subsequent PR will make things match.

**Comment by mansona** [comment]
I just wanted to add a quick summary of various discussions myself and @rwwagner90 were having about this issue: 

I would much prefer this to be implemented using the standard [Error Substate](https://guides.emberjs.com/v2.18.0/routing/loading-and-error-substates/#toc_code-error-code-substates) with some sort of logic in the `error.hbs` that decides to show a "Whoops 404" page or "Unknown error". This way we can cover all errors with minimal duplication, and it also is a good example of how to use Error Substates 😄

**Comment by jenweber** [comment]
Hey @rwwagner90 , my apologies for the confusion over the 404 page. I was unfamiliar with error substates and didn't actually get the gist of what @mansona was asking for when I wrote up the issue. I still have a lot to learn about Ember, and sometimes I miss things. Consider my initial writeup to be incorrect.

We'll do better next time!
