### ISSUE TITLE
Migrate header and footer from ember-styleguide

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-app#18]
To Do:
- [x] copy/paste from [css](https://github.com/ember-learn/glimmer-styleguide/blob/a96a0b243420d5e916de0942912d25f34d806aa4/src/ui/styles/main-footer.scss) and [template](https://github.com/ember-learn/glimmer-styleguide/blob/a96a0b243420d5e916de0942912d25f34d806aa4/src/ui/components/main-footer/template.hbs)
- [x] make styling adjustments
- [ ] swap out templates, css, etc with https://github.com/emberjs/website/pull/3157 once it is ready to ship (more copy/paste)
- [ ] replace with components from [ember-styleguide](https://github.com/ember-learn/ember-styleguide) once they ship

**Comment by jenweber** [comment]
Results of integrating ember-styleguide. Top is live website, bottom is my work running locally
![screen shot 2018-01-20 at 4 25 14 pm](https://user-images.githubusercontent.com/16627268/35188155-c7a76dce-fdfe-11e7-9e8c-d7352180c97d.png)

left my work, right current site
![screen shot 2018-01-20 at 4 27 58 pm](https://user-images.githubusercontent.com/16627268/35188162-f06c36fe-fdfe-11e7-919f-5aa0da229ccd.png)

**Comment by jenweber** [comment]
Migrated header - top is live, bottom is styling imported from glimmer-styleguide
![screen shot 2018-01-20 at 4 45 32 pm](https://user-images.githubusercontent.com/16627268/35188335-7c6b15ce-fe01-11e7-9f9f-c02fbd6152b4.png)

**Comment by sivakumar-kailasam** [comment]
We've swapped out the local components with the ones from ember-styleguide
