### ISSUE TITLE
Navigating to a non-existant route results in a blank screen

### ISSUE THREAD

**Issue by anotheredward** [ember-learn/guides-app#203]
Repro:
1. Navigate to: `https://guides.emberjs.com/v1.12.0/nonsense/route/`
2. Note that the application doesn't render

Proposed solution:
1. Navigate to: `https://guides.emberjs.com/v1.12.0/nonsense/route/`
2. Be redirected to `https://guides.emberjs.com/v1.12.0/`
3. Application renders

If the version also happens to be invalid, we can redirect to `/release/` by default, this way at least the application renders something useful.

This is related, but not the same as: #132 

Does this potential fix work or would the team prefer a 404, as in the other example?

**Comment by mansona** [comment]
Hi @anotheredward thanks for the issue 🎉 

So the main thing that is missing here is that you **should** see the 404 page when you go to a `/nonsense/route`. That is a bug and it has been addressed with https://github.com/ember-learn/guides-app/pull/204 🎉 

As for changing the behaviour, I think it would make the most sense to discuss that on the other issue https://github.com/ember-learn/guides-app/issues/132 👍 

Thanks again for the issue report 😄
