### ISSUE TITLE
Testing wishlist

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-app#34]
(other maintainers are welcome to edit this directly)

- [x] recent-ish guides nav by previous-next links
- [x] cookbook nav by previous-next links
- [x] navigation by TOC
- [x] navigation by dropdown
- [x] `current` url works

**Comment by mansona** [comment]
@jenweber I merged your last PR, does that close this issue? 🤔

**Comment by jenweber** [comment]
Well, what other things do you check by hand to see if they are working? If this covers all the bases, you can close.

**Comment by mansona** [comment]
This covers more than what I usually test when I do it manually 😂 or rather I don't tend to test all these things every time I test.

I'll close and we can discuss other testing wishlists at a later stage 👍
