### ISSUE TITLE
Stop ember-algolia from needing ember-browserify so it doesn't cause guides-app to install browserify

### ISSUE THREAD

**Issue by mansona** [ember-learn/guides-app#42]
We might be able to get some inspiration here: https://github.com/ember-learn/deprecation-app/issues/56

**Comment by sivakumar-kailasam** [comment]
@mansona can you raise this in the ember-algolia repo as well?

**Comment by mansona** [comment]
@sivakumar-kailasam that was essentially my "to-do" item for this once we get to the "post-release" phase (see project)

I'm planning to do this as an actual PR over there 👍

**Comment by mansona** [comment]
This is now fixed because we're using algolia directly and auto-import 👍
