### ISSUE TITLE
Clarify the expected behaviour of the search on the guides page

### ISSUE THREAD

**Issue by mansona** [ember-learn/guides-app#51]
I'm trying to clarify if we only want **guides** results when searching on https://guides.emberjs.com/

I seem to remember that there were some discussions that this is expected behaviour i.e. that you cannot search for API results when you're on the guides. I'm not saying it's the desired behaviour (I know we want to unify all of this) but I'm under the impression that we are **expecting** it to work this way right now.

**Comment by acorncom** [comment]
That it only shows guides results is expected. Not desired long-term, but needn’t block us from launching. Thanks for checking 🙂

**Comment by mansona** [comment]
I'm closing this issue because we have actually _clarified_ the plans for the current incarnation of the search in guides 👍 Any future plans can be created as a new set of issues/projects
